.TH nowsbe-plugin "8" "27 Aug 2010" "nowsbe-plugin" "Support Utilities Manual"
.SH NAME
nows-plugin \- Novell Open Workgroup Suite Small Business Edition Plugins for 
.BR supportconfig (8)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. This plugin extends supportconfig's functionality to include Novell Open Workgroup Suite
Small Business Edition additional feature information. Supportconfig saves the plugin output in its log directory as plugin-nowsbe_*.txt.

.SH SUPPORTCONFIG PLUGIN FOR NOWS FILES
.I /opt/supportconfig/plugins/nows_amanda
.RS
Amanda network backup solution
.RE
.I /opt/supportconfig/plugins/nows_clamav
.RS
Clam AntiVirus
.RE
.I /opt/supportconfig/plugins/nows_dlu_pgina
.RS
Simba DLU/pGina Component
.RE
.I /opt/supportconfig/plugins/nows_helpdesk
.RS
Help Desk
.RE
.I /opt/supportconfig/plugins/nows_hylafax
.RS
Hylafax Faxing solution
.RE
.I /opt/supportconfig/plugins/nows_mailscanner
.RS
MailScanner scans email content
.RE
.I /opt/supportconfig/plugins/nows_openvpn
.RS
OpenVPN virtual private network solution
.RE
.I /opt/supportconfig/plugins/nows_simba
.RS
Simba application server
.RE
.SH AUTHOR
Jason Record <jrecord@novell.com>
.SH REPORTING BUGS
Please submit bug fixes, comments or enhancement requests via: 
.B http://code.google.com/p/supportutils-plugin-nowsbe/issues/list
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
